name: Build and Release Applications

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  actions: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build macOS App
        run: |
          python -m pip install -r requirements.txt py2app
          python setup.py py2app
          cd dist && zip -r "MilibrisReaderToPDF-macOS.zip" "Milibris Reader to PDF.app"
      - name: Upload macOS Build
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: dist/MilibrisReaderToPDF-macOS.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build Linux App
        run: |
          python -m pip install -r requirements.txt pyinstaller
          pyinstaller build.spec
          cd dist && tar -czf MilibrisReaderToPDF-linux.tar.gz MilibrisReaderToPDF
      - name: Upload Linux Build
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/MilibrisReaderToPDF-linux.tar.gz

  release:
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          gh release create "$VERSION" \
            --title "Release $VERSION" \
            --notes "Release $VERSION" \
            dist/MilibrisReaderToPDF-macOS.zip \
            dist/MilibrisReaderToPDF-linux.tar.gz
