name: Build and Release macOS Application

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build macOS App
        run: |
          source .venv/bin/activate
          python setup.py py2app
          cd dist
          zip -r "Milibris Reader to PDF.zip" "Milibris Reader to PDF.app"

      - name: Create and Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          
          # Create release using GitHub CLI
          gh release create $VERSION \
            --title "Release $VERSION" \
            --notes "Release $VERSION" \
            --draft=false \
            "dist/Milibris Reader to PDF.zip"
