name: Build and Upload macOS Application

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
    # You can add more branches or events as needed

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Build the macOS Application using py2app
      - name: Build macOS App
        run: |
          source venv/bin/activate
          python setup.py py2app

      # 5. Upload the .app Bundle as an Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MilibrisReaderToPDF-macOS
          path: "dist/Milibris Reader to PDF.app"